### ISSUE TITLE
Folder structure for seminars might get cluttered for future

### ISSUE THREAD

**Issue by akulmehta** [glycoinfo/GLIC#4]
The current folder structure means that the seminar series gets a URL of https://glic.glycoinfo.org/seminar/

Since we plan to have more than one series (hopefully) in the future, it may be better to reorganize the folder structure so that the glycan array special topic gets the url https://glic.glycoinfo.org/seminar/glycan-arrays

If agreed I can refactor for this.

**Comment by ReneRanzinger** [comment]
That is one idea. I thought that the /seminar/ would always show the ongoing and upcoming webinars. Later we would have a link on that page "Show past seminars" that goes to a long list of previous webinars.

**Comment by akulmehta** [comment]
@ReneRanzinger the /seminar/ page can have a section for `Upcoming Seminars` with links to the seminar series coming up and another section for `Past Seminars` where we have links to the past. Thoughts?

**Comment by ReneRanzinger** [comment]
@akulmehta If I understand you correctly the /seminar/ page is just a hub to link to Upcoming and past seminars. I personal dont like that because I am lazy. If I am on the GLIC homepage and want to get to the seminars I have to click twice (home-> seminar -> upcoming seminar) to get what I want. Therefore I would like to keep the upcoming seminars on this page and have the past events on a different page (different page: otherwise that page might become long). 

And yes I know that with this setup you have to click twice to get to the past events ;-). But I think its more likely for people to search for ongoing and upcoming events rather than past events.

**Comment by akulmehta** [comment]
As you wish. For now it is fine I will close issue. We can review when we have the next seminar series.
